import Foundation

struct Surah: Identifiable, Codable {
    let id: Int
    let name: String
    let nameEn: String
    let verses: Int
    let page: Int
    let type: String
}

let allSurahs: [Surah] = [
    Surah(id: 1,   name: "الفاتحة",         nameEn: "Al-Fatihah",      verses: 7,   page: 1,   type: "مكية"),
    Surah(id: 2,   name: "البقرة",           nameEn: "Al-Baqarah",      verses: 286, page: 2,   type: "مدنية"),
    Surah(id: 3,   name: "آل عمران",          nameEn: "Aal-Imran",       verses: 200, page: 50,  type: "مدنية"),
    Surah(id: 4,   name: "النساء",           nameEn: "An-Nisa",         verses: 176, page: 77,  type: "مدنية"),
    Surah(id: 5,   name: "المائدة",          nameEn: "Al-Maidah",       verses: 120, page: 106, type: "مدنية"),
    Surah(id: 6,   name: "الأنعام",          nameEn: "Al-Anam",         verses: 165, page: 128, type: "مكية"),
    Surah(id: 7,   name: "الأعراف",          nameEn: "Al-Araf",         verses: 206, page: 151, type: "مكية"),
    Surah(id: 8,   name: "الأنفال",          nameEn: "Al-Anfal",        verses: 75,  page: 177, type: "مدنية"),
    Surah(id: 9,   name: "التوبة",           nameEn: "At-Tawbah",       verses: 129, page: 187, type: "مدنية"),
    Surah(id: 10,  name: "يونس",             nameEn: "Yunus",           verses: 109, page: 208, type: "مكية"),
    Surah(id: 11,  name: "هود",              nameEn: "Hud",             verses: 123, page: 221, type: "مكية"),
    Surah(id: 12,  name: "يوسف",             nameEn: "Yusuf",           verses: 111, page: 235, type: "مكية"),
    Surah(id: 13,  name: "الرعد",            nameEn: "Ar-Rad",          verses: 43,  page: 249, type: "مدنية"),
    Surah(id: 14,  name: "إبراهيم",          nameEn: "Ibrahim",         verses: 52,  page: 255, type: "مكية"),
    Surah(id: 15,  name: "الحجر",            nameEn: "Al-Hijr",         verses: 99,  page: 262, type: "مكية"),
    Surah(id: 16,  name: "النحل",            nameEn: "An-Nahl",         verses: 128, page: 267, type: "مكية"),
    Surah(id: 17,  name: "الإسراء",          nameEn: "Al-Isra",         verses: 111, page: 282, type: "مكية"),
    Surah(id: 18,  name: "الكهف",            nameEn: "Al-Kahf",         verses: 110, page: 293, type: "مكية"),
    Surah(id: 19,  name: "مريم",             nameEn: "Maryam",          verses: 98,  page: 305, type: "مكية"),
    Surah(id: 20,  name: "طه",               nameEn: "Ta-Ha",           verses: 135, page: 312, type: "مكية"),
    Surah(id: 21,  name: "الأنبياء",         nameEn: "Al-Anbiya",       verses: 112, page: 322, type: "مكية"),
    Surah(id: 22,  name: "الحج",             nameEn: "Al-Hajj",         verses: 78,  page: 332, type: "مدنية"),
    Surah(id: 23,  name: "المؤمنون",         nameEn: "Al-Muminun",      verses: 118, page: 342, type: "مكية"),
    Surah(id: 24,  name: "النور",            nameEn: "An-Nur",          verses: 64,  page: 350, type: "مدنية"),
    Surah(id: 25,  name: "الفرقان",          nameEn: "Al-Furqan",       verses: 77,  page: 359, type: "مكية"),
    Surah(id: 26,  name: "الشعراء",          nameEn: "Ash-Shuara",      verses: 227, page: 367, type: "مكية"),
    Surah(id: 27,  name: "النمل",            nameEn: "An-Naml",         verses: 93,  page: 377, type: "مكية"),
    Surah(id: 28,  name: "القصص",            nameEn: "Al-Qasas",        verses: 88,  page: 385, type: "مكية"),
    Surah(id: 29,  name: "العنكبوت",         nameEn: "Al-Ankabut",      verses: 69,  page: 396, type: "مكية"),
    Surah(id: 30,  name: "الروم",            nameEn: "Ar-Rum",          verses: 60,  page: 404, type: "مكية"),
    Surah(id: 31,  name: "لقمان",            nameEn: "Luqman",          verses: 34,  page: 411, type: "مكية"),
    Surah(id: 32,  name: "السجدة",           nameEn: "As-Sajdah",       verses: 30,  page: 415, type: "مكية"),
    Surah(id: 33,  name: "الأحزاب",          nameEn: "Al-Ahzab",        verses: 73,  page: 418, type: "مدنية"),
    Surah(id: 34,  name: "سبأ",              nameEn: "Saba",            verses: 54,  page: 428, type: "مكية"),
    Surah(id: 35,  name: "فاطر",             nameEn: "Fatir",           verses: 45,  page: 434, type: "مكية"),
    Surah(id: 36,  name: "يس",               nameEn: "Ya-Sin",          verses: 83,  page: 440, type: "مكية"),
    Surah(id: 37,  name: "الصافات",          nameEn: "As-Saffat",       verses: 182, page: 446, type: "مكية"),
    Surah(id: 38,  name: "ص",                nameEn: "Sad",             verses: 88,  page: 453, type: "مكية"),
    Surah(id: 39,  name: "الزمر",            nameEn: "Az-Zumar",        verses: 75,  page: 458, type: "مكية"),
    Surah(id: 40,  name: "غافر",             nameEn: "Ghafir",          verses: 85,  page: 467, type: "مكية"),
    Surah(id: 41,  name: "فصلت",             nameEn: "Fussilat",        verses: 54,  page: 477, type: "مكية"),
    Surah(id: 42,  name: "الشورى",           nameEn: "Ash-Shura",       verses: 53,  page: 483, type: "مكية"),
    Surah(id: 43,  name: "الزخرف",           nameEn: "Az-Zukhruf",      verses: 89,  page: 489, type: "مكية"),
    Surah(id: 44,  name: "الدخان",           nameEn: "Ad-Dukhan",       verses: 59,  page: 496, type: "مكية"),
    Surah(id: 45,  name: "الجاثية",          nameEn: "Al-Jathiyah",     verses: 37,  page: 499, type: "مكية"),
    Surah(id: 46,  name: "الأحقاف",          nameEn: "Al-Ahqaf",        verses: 35,  page: 502, type: "مكية"),
    Surah(id: 47,  name: "محمد",             nameEn: "Muhammad",        verses: 38,  page: 507, type: "مدنية"),
    Surah(id: 48,  name: "الفتح",            nameEn: "Al-Fath",         verses: 29,  page: 511, type: "مدنية"),
    Surah(id: 49,  name: "الحجرات",          nameEn: "Al-Hujurat",      verses: 18,  page: 515, type: "مدنية"),
    Surah(id: 50,  name: "ق",                nameEn: "Qaf",             verses: 45,  page: 518, type: "مكية"),
    Surah(id: 51,  name: "الذاريات",         nameEn: "Adh-Dhariyat",    verses: 60,  page: 520, type: "مكية"),
    Surah(id: 52,  name: "الطور",            nameEn: "At-Tur",          verses: 49,  page: 523, type: "مكية"),
    Surah(id: 53,  name: "النجم",            nameEn: "An-Najm",         verses: 62,  page: 526, type: "مكية"),
    Surah(id: 54,  name: "القمر",            nameEn: "Al-Qamar",        verses: 55,  page: 528, type: "مكية"),
    Surah(id: 55,  name: "الرحمن",           nameEn: "Ar-Rahman",       verses: 78,  page: 531, type: "مدنية"),
    Surah(id: 56,  name: "الواقعة",          nameEn: "Al-Waqiah",       verses: 96,  page: 534, type: "مكية"),
    Surah(id: 57,  name: "الحديد",           nameEn: "Al-Hadid",        verses: 29,  page: 537, type: "مدنية"),
    Surah(id: 58,  name: "المجادلة",         nameEn: "Al-Mujadila",     verses: 22,  page: 542, type: "مدنية"),
    Surah(id: 59,  name: "الحشر",            nameEn: "Al-Hashr",        verses: 24,  page: 545, type: "مدنية"),
    Surah(id: 60,  name: "الممتحنة",         nameEn: "Al-Mumtahanah",   verses: 13,  page: 549, type: "مدنية"),
    Surah(id: 61,  name: "الصف",             nameEn: "As-Saf",          verses: 14,  page: 551, type: "مدنية"),
    Surah(id: 62,  name: "الجمعة",           nameEn: "Al-Jumuah",       verses: 11,  page: 553, type: "مدنية"),
    Surah(id: 63,  name: "المنافقون",        nameEn: "Al-Munafiqun",    verses: 11,  page: 554, type: "مدنية"),
    Surah(id: 64,  name: "التغابن",          nameEn: "At-Taghabun",     verses: 18,  page: 556, type: "مدنية"),
    Surah(id: 65,  name: "الطلاق",           nameEn: "At-Talaq",        verses: 12,  page: 558, type: "مدنية"),
    Surah(id: 66,  name: "التحريم",          nameEn: "At-Tahrim",       verses: 12,  page: 560, type: "مدنية"),
    Surah(id: 67,  name: "الملك",            nameEn: "Al-Mulk",         verses: 30,  page: 562, type: "مكية"),
    Surah(id: 68,  name: "القلم",            nameEn: "Al-Qalam",        verses: 52,  page: 564, type: "مكية"),
    Surah(id: 69,  name: "الحاقة",           nameEn: "Al-Haqqah",       verses: 52,  page: 566, type: "مكية"),
    Surah(id: 70,  name: "المعارج",          nameEn: "Al-Maarij",       verses: 44,  page: 568, type: "مكية"),
    Surah(id: 71,  name: "نوح",              nameEn: "Nuh",             verses: 28,  page: 570, type: "مكية"),
    Surah(id: 72,  name: "الجن",             nameEn: "Al-Jinn",         verses: 28,  page: 572, type: "مكية"),
    Surah(id: 73,  name: "المزمل",           nameEn: "Al-Muzzammil",    verses: 20,  page: 574, type: "مكية"),
    Surah(id: 74,  name: "المدثر",           nameEn: "Al-Muddaththir",  verses: 56,  page: 575, type: "مكية"),
    Surah(id: 75,  name: "القيامة",          nameEn: "Al-Qiyamah",      verses: 40,  page: 577, type: "مكية"),
    Surah(id: 76,  name: "الإنسان",          nameEn: "Al-Insan",        verses: 31,  page: 578, type: "مدنية"),
    Surah(id: 77,  name: "المرسلات",         nameEn: "Al-Mursalat",     verses: 50,  page: 580, type: "مكية"),
    Surah(id: 78,  name: "النبأ",            nameEn: "An-Naba",         verses: 40,  page: 582, type: "مكية"),
    Surah(id: 79,  name: "النازعات",         nameEn: "An-Naziat",       verses: 46,  page: 583, type: "مكية"),
    Surah(id: 80,  name: "عبس",              nameEn: "Abasa",           verses: 42,  page: 585, type: "مكية"),
    Surah(id: 81,  name: "التكوير",          nameEn: "At-Takwir",       verses: 29,  page: 586, type: "مكية"),
    Surah(id: 82,  name: "الانفطار",         nameEn: "Al-Infitar",      verses: 19,  page: 587, type: "مكية"),
    Surah(id: 83,  name: "المطففين",         nameEn: "Al-Mutaffifin",   verses: 36,  page: 587, type: "مكية"),
    Surah(id: 84,  name: "الانشقاق",         nameEn: "Al-Inshiqaq",     verses: 25,  page: 589, type: "مكية"),
    Surah(id: 85,  name: "البروج",           nameEn: "Al-Buruj",        verses: 22,  page: 590, type: "مكية"),
    Surah(id: 86,  name: "الطارق",           nameEn: "At-Tariq",        verses: 17,  page: 591, type: "مكية"),
    Surah(id: 87,  name: "الأعلى",           nameEn: "Al-Ala",          verses: 19,  page: 591, type: "مكية"),
    Surah(id: 88,  name: "الغاشية",          nameEn: "Al-Ghashiyah",    verses: 26,  page: 592, type: "مكية"),
    Surah(id: 89,  name: "الفجر",            nameEn: "Al-Fajr",         verses: 30,  page: 593, type: "مكية"),
    Surah(id: 90,  name: "البلد",            nameEn: "Al-Balad",        verses: 20,  page: 594, type: "مكية"),
    Surah(id: 91,  name: "الشمس",            nameEn: "Ash-Shams",       verses: 15,  page: 595, type: "مكية"),
    Surah(id: 92,  name: "الليل",            nameEn: "Al-Layl",         verses: 21,  page: 595, type: "مكية"),
    Surah(id: 93,  name: "الضحى",            nameEn: "Ad-Duha",         verses: 11,  page: 596, type: "مكية"),
    Surah(id: 94,  name: "الشرح",            nameEn: "Ash-Sharh",       verses: 8,   page: 596, type: "مكية"),
    Surah(id: 95,  name: "التين",            nameEn: "At-Tin",          verses: 8,   page: 597, type: "مكية"),
    Surah(id: 96,  name: "العلق",            nameEn: "Al-Alaq",         verses: 19,  page: 597, type: "مكية"),
    Surah(id: 97,  name: "القدر",            nameEn: "Al-Qadr",         verses: 5,   page: 598, type: "مكية"),
    Surah(id: 98,  name: "البينة",           nameEn: "Al-Bayyinah",     verses: 8,   page: 598, type: "مدنية"),
    Surah(id: 99,  name: "الزلزلة",          nameEn: "Az-Zalzalah",     verses: 8,   page: 599, type: "مدنية"),
    Surah(id: 100, name: "العاديات",         nameEn: "Al-Adiyat",       verses: 11,  page: 599, type: "مكية"),
    Surah(id: 101, name: "القارعة",          nameEn: "Al-Qariah",       verses: 11,  page: 600, type: "مكية"),
    Surah(id: 102, name: "التكاثر",          nameEn: "At-Takathur",     verses: 8,   page: 600, type: "مكية"),
    Surah(id: 103, name: "العصر",            nameEn: "Al-Asr",          verses: 3,   page: 601, type: "مكية"),
    Surah(id: 104, name: "الهمزة",           nameEn: "Al-Humazah",      verses: 9,   page: 601, type: "مكية"),
    Surah(id: 105, name: "الفيل",            nameEn: "Al-Fil",          verses: 5,   page: 601, type: "مكية"),
    Surah(id: 106, name: "قريش",             nameEn: "Quraysh",         verses: 4,   page: 602, type: "مكية"),
    Surah(id: 107, name: "الماعون",          nameEn: "Al-Maun",         verses: 7,   page: 602, type: "مكية"),
    Surah(id: 108, name: "الكوثر",           nameEn: "Al-Kawthar",      verses: 3,   page: 602, type: "مكية"),
    Surah(id: 109, name: "الكافرون",         nameEn: "Al-Kafirun",      verses: 6,   page: 603, type: "مكية"),
    Surah(id: 110, name: "النصر",            nameEn: "An-Nasr",         verses: 3,   page: 603, type: "مدنية"),
    Surah(id: 111, name: "المسد",            nameEn: "Al-Masad",        verses: 5,   page: 603, type: "مكية"),
    Surah(id: 112, name: "الإخلاص",          nameEn: "Al-Ikhlas",       verses: 4,   page: 604, type: "مكية"),
    Surah(id: 113, name: "الفلق",            nameEn: "Al-Falaq",        verses: 5,   page: 604, type: "مكية"),
    Surah(id: 114, name: "الناس",            nameEn: "An-Nas",          verses: 6,   page: 604, type: "مكية"),
]
